version: 2
updates:
  # Maintain dependencies for npm packages
  - package-ecosystem: 'npm'
    pull-request-branch-name:
      separator: '-'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    pull-request-branch-name:
      separator: '-'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
